# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calendar.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calendar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63\x61lendar.proto\x12\x08\x63\x61lendar\"\xda\x01\n\x0c\x45ventDetails\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nstart_time\x18\x04 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x05 \x01(\t\x12\x10\n\x08location\x18\x06 \x01(\t\x12\x11\n\tattendees\x18\x07 \x03(\t\x12\x11\n\torganizer\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\x12\x12\n\ncreated_at\x18\n \x01(\t\x12\x12\n\nupdated_at\x18\x0b \x01(\t\" \n\x0c\x45ventRequest\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\"X\n\rEventResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12%\n\x05\x65vent\x18\x03 \x01(\x0b\x32\x16.calendar.EventDetails\"W\n\x0c\x45ventsFilter\x12\x12\n\nstart_date\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x02 \x01(\t\x12\x11\n\torganizer\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\"H\n\tEventList\x12&\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x16.calendar.EventDetails\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x32\xc8\x02\n\x0f\x43\x61lendarService\x12>\n\x0b\x43reateEvent\x12\x16.calendar.EventDetails\x1a\x17.calendar.EventResponse\x12:\n\x08GetEvent\x12\x16.calendar.EventRequest\x1a\x16.calendar.EventDetails\x12>\n\x0bUpdateEvent\x12\x16.calendar.EventDetails\x1a\x17.calendar.EventResponse\x12>\n\x0b\x44\x65leteEvent\x12\x16.calendar.EventRequest\x1a\x17.calendar.EventResponse\x12\x39\n\nListEvents\x12\x16.calendar.EventsFilter\x1a\x13.calendar.EventListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calendar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTDETAILS']._serialized_start=29
  _globals['_EVENTDETAILS']._serialized_end=247
  _globals['_EVENTREQUEST']._serialized_start=249
  _globals['_EVENTREQUEST']._serialized_end=281
  _globals['_EVENTRESPONSE']._serialized_start=283
  _globals['_EVENTRESPONSE']._serialized_end=371
  _globals['_EVENTSFILTER']._serialized_start=373
  _globals['_EVENTSFILTER']._serialized_end=460
  _globals['_EVENTLIST']._serialized_start=462
  _globals['_EVENTLIST']._serialized_end=534
  _globals['_CALENDARSERVICE']._serialized_start=537
  _globals['_CALENDARSERVICE']._serialized_end=865
# @@protoc_insertion_point(module_scope)
